#Runs bi-weekly
name: Launch Wizard

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 7 1,15 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-session-name: GithubActions 
      
      # Runs a set of commands using the runners shell
      - name: test
        run: |
          aws --version
          aws s3 cp s3://${{ secrets.STAGING_S3 }}/S4TESTRUN1-1689931791648/ ./ --recursive
          Timestamp=$(date +%s)
          LogGroupName=LaunchWizard-S4TESTRUN-$Timestamp
          UniqueID=$Timestamp
          echo $Timestamp
          aws cloudformation deploy --stack-name $LogGroupName --template-file S4TESTRUN1-SapNWOnHanaSingle-template.json --parameter-overrides HANAMasterPassKey=$HANAMasterPassKey Timestamp=$Timestamp LogGroupName=$LogGroupName UniqueID=$UniqueID  --s3-bucket ${{ secrets.STAGING_S3 }} --capabilities CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM CAPABILITY_IAM